### ISSUE TITLE
api 

### ISSUE THREAD

**Issue by CYBki** [florian-kalisch/auto-mindmapping#1]
Hi florian, I installed it on my computer and the project opened, I clicked the create button, but it didn't work, I wonder if there is a place where I need to enter the api key.

**Comment by florian-kalisch** [comment]
Hi, there are two sections "Mindmapping" and "Settings" (this "menu" could be nicer). If you click on "Settings", you can enter the API key / token under "OpenAI Token".
Just for your information ( but it should be obvious): Using the API will result in request-based costs ( it is not part of the ChatGPT Subscription).

**Comment by CYBki** [comment]
Thanks
